services:
  - type: web
    name: insurance-claim-service
    runtime: docker
    rootDir: Backend/Claim-ServiceAPI
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health/ready
    autoDeployTrigger: commit
