// <auto-generated />
using System;
using Claim_ServiceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Claim_ServiceAPI.Migrations
{
    [DbContext(typeof(ClaimDbContext))]
    [Migration("20260731065224_InitialClaimSchema")]
    partial class InitialClaimSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Claim", b =>
                {
                    b.Property<long>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClaimId"));

                    b.Property<decimal>("ApprovedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("AssignedToUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CauseOfLoss")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ClaimAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ClaimStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ClosureReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DeductionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("FraudRiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly>("IncidentDate")
                        .HasColumnType("date");

                    b.Property<string>("IncidentLocation")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<TimeOnly?>("IncidentTime")
                        .HasColumnType("time");

                    b.Property<DateOnly?>("IntimationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LossDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PolicyId")
                        .HasColumnType("bigint");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("SettledAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("VersionNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("ClaimId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ClaimNumber")
                        .IsUnique();

                    b.HasIndex("ClaimStatusId");

                    b.HasIndex("ClaimTypeId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("PriorityId");

                    b.ToTable("Claim", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.ClaimActionHistory", b =>
                {
                    b.Property<long>("ClaimActionHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClaimActionHistoryId"));

                    b.Property<DateTimeOffset>("ActionAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ActionByUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("ActionTypeId")
                        .HasColumnType("int");

                    b.Property<long>("ClaimId")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClaimActionHistoryId");

                    b.HasIndex("ActionByUserId");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimActionHistory", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.ClaimAssessment", b =>
                {
                    b.Property<long>("ClaimAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClaimAssessmentId"));

                    b.Property<decimal>("AssessedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("AssessmentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AssessmentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("AssessmentSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AssessorUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClaimId")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("DepreciationAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedLossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InternalRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("LiabilityPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RecommendedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalvageAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("VersionNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("ClaimAssessmentId");

                    b.HasIndex("AssessmentStatusId");

                    b.HasIndex("AssessorUserId");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimAssessment", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.ClaimDocument", b =>
                {
                    b.Property<long>("ClaimDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClaimDocumentId"));

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("ClaimId")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StorageProvider")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UploadedByUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("VerificationStatusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("VerifiedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("VersionNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("ClaimDocumentId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("VerificationStatusId");

                    b.ToTable("ClaimDocument", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.ClaimParty", b =>
                {
                    b.Property<long>("ClaimPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClaimPartyId"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ClaimId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PartyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("VersionNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("ClaimPartyId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("PartyTypeId");

                    b.ToTable("ClaimParty", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.ClaimSettlement", b =>
                {
                    b.Property<long>("ClaimSettlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClaimSettlementId"));

                    b.Property<decimal>("ApprovedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ClaimId")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DeductionsAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("NetPayableAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaidToAccountMasked")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaidToName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PaymentReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("SettlementDate")
                        .HasColumnType("date");

                    b.Property<int>("SettlementTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("VersionNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("ClaimSettlementId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("PaymentStatusId");

                    b.HasIndex("SettlementTypeId");

                    b.ToTable("ClaimSettlement", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.ClaimStatusHistory", b =>
                {
                    b.Property<long>("ClaimStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClaimStatusHistoryId"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ChangedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClaimId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CurrentStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Source")
                        .HasColumnType("int");

                    b.HasKey("ClaimStatusHistoryId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CurrentStatusId");

                    b.HasIndex("PreviousStatusId");

                    b.ToTable("ClaimStatusHistory", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.AssessmentStatus", b =>
                {
                    b.Property<int>("AssessmentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AssessmentStatusId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AssessmentStatus", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimActionType", b =>
                {
                    b.Property<int>("ActionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ActionTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ClaimActionType", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimDocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DocumentTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ClaimDocumentType", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimPartyType", b =>
                {
                    b.Property<int>("PartyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PartyTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ClaimPartyType", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimPriority", b =>
                {
                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PriorityId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ClaimPriority", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimStatus", b =>
                {
                    b.Property<int>("ClaimStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsTerminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.HasKey("ClaimStatusId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ClaimStatus", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimType", b =>
                {
                    b.Property<int>("ClaimTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClaimTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ClaimType", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimVerificationStatus", b =>
                {
                    b.Property<int>("VerificationStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VerificationStatusId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ClaimVerificationStatus", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentStatusId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PaymentStatus", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.SettlementType", b =>
                {
                    b.Property<int>("SettlementTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SettlementTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SettlementType", (string)null);
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Claim", b =>
                {
                    b.HasOne("Claim_ServiceAPI.Models.Claims.Lookups.ClaimStatus", "ClaimStatus")
                        .WithMany("Claims")
                        .HasForeignKey("ClaimStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Claim_ServiceAPI.Models.Claims.Lookups.ClaimType", "ClaimType")
                        .WithMany("Claims")
                        .HasForeignKey("ClaimTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Claim_ServiceAPI.Models.Claims.Lookups.ClaimPriority", "Priority")
                        .WithMany("Claims")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClaimStatus");

                    b.Navigation("ClaimType");

                    b.Navigation("Priority");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.ClaimActionHistory", b =>
                {
                    b.HasOne("Claim_ServiceAPI.Models.Claims.Lookups.ClaimActionType", "ActionType")
                        .WithMany("ActionHistories")
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Claim_ServiceAPI.Models.Claims.Claim", "Claim")
                        .WithMany("ActionHistory")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionType");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.ClaimAssessment", b =>
                {
                    b.HasOne("Claim_ServiceAPI.Models.Claims.Lookups.AssessmentStatus", "AssessmentStatus")
                        .WithMany("Assessments")
                        .HasForeignKey("AssessmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Claim_ServiceAPI.Models.Claims.Claim", "Claim")
                        .WithMany("Assessments")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentStatus");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.ClaimDocument", b =>
                {
                    b.HasOne("Claim_ServiceAPI.Models.Claims.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Claim_ServiceAPI.Models.Claims.Lookups.ClaimDocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Claim_ServiceAPI.Models.Claims.Lookups.ClaimVerificationStatus", "VerificationStatus")
                        .WithMany("Documents")
                        .HasForeignKey("VerificationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("DocumentType");

                    b.Navigation("VerificationStatus");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.ClaimParty", b =>
                {
                    b.HasOne("Claim_ServiceAPI.Models.Claims.Claim", "Claim")
                        .WithMany("Parties")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Claim_ServiceAPI.Models.Claims.Lookups.ClaimPartyType", "PartyType")
                        .WithMany("Parties")
                        .HasForeignKey("PartyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("PartyType");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.ClaimSettlement", b =>
                {
                    b.HasOne("Claim_ServiceAPI.Models.Claims.Claim", "Claim")
                        .WithMany("Settlements")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Claim_ServiceAPI.Models.Claims.Lookups.PaymentStatus", "PaymentStatus")
                        .WithMany("Settlements")
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Claim_ServiceAPI.Models.Claims.Lookups.SettlementType", "SettlementType")
                        .WithMany("Settlements")
                        .HasForeignKey("SettlementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("PaymentStatus");

                    b.Navigation("SettlementType");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.ClaimStatusHistory", b =>
                {
                    b.HasOne("Claim_ServiceAPI.Models.Claims.Claim", "Claim")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Claim_ServiceAPI.Models.Claims.Lookups.ClaimStatus", "CurrentStatus")
                        .WithMany()
                        .HasForeignKey("CurrentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Claim_ServiceAPI.Models.Claims.Lookups.ClaimStatus", "PreviousStatus")
                        .WithMany()
                        .HasForeignKey("PreviousStatusId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Claim");

                    b.Navigation("CurrentStatus");

                    b.Navigation("PreviousStatus");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Claim", b =>
                {
                    b.Navigation("ActionHistory");

                    b.Navigation("Assessments");

                    b.Navigation("Documents");

                    b.Navigation("Parties");

                    b.Navigation("Settlements");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.AssessmentStatus", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimActionType", b =>
                {
                    b.Navigation("ActionHistories");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimDocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimPartyType", b =>
                {
                    b.Navigation("Parties");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimPriority", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimStatus", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimType", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.ClaimVerificationStatus", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.PaymentStatus", b =>
                {
                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("Claim_ServiceAPI.Models.Claims.Lookups.SettlementType", b =>
                {
                    b.Navigation("Settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
